/**
 * Dictionnaire bidirectionnel des noms Pokemon FR <-> EN
 * Couvre les 9 generations (1025+ Pokemon)
 * Source: noms officiels Pokemon
 */

// Format: [anglais, francais]
const NAME_PAIRS: [string, string][] = [
  // ===== GENERATION 1 (Kanto) =====
  ["Bulbasaur", "Bulbizarre"],
  ["Ivysaur", "Herbizarre"],
  ["Venusaur", "Florizarre"],
  ["Charmander", "Salamèche"],
  ["Charmeleon", "Reptincel"],
  ["Charizard", "Dracaufeu"],
  ["Squirtle", "Carapuce"],
  ["Wartortle", "Carabaffe"],
  ["Blastoise", "Tortank"],
  ["Caterpie", "Chenipan"],
  ["Metapod", "Chrysacier"],
  ["Butterfree", "Papilusion"],
  ["Weedle", "Aspicot"],
  ["Kakuna", "Coconfort"],
  ["Beedrill", "Dardargnan"],
  ["Pidgey", "Roucool"],
  ["Pidgeotto", "Roucoups"],
  ["Pidgeot", "Roucarnage"],
  ["Rattata", "Rattata"],
  ["Raticate", "Rattatac"],
  ["Spearow", "Piafabec"],
  ["Fearow", "Rapasdepic"],
  ["Ekans", "Abo"],
  ["Arbok", "Arbok"],
  ["Pikachu", "Pikachu"],
  ["Raichu", "Raichu"],
  ["Sandshrew", "Sabelette"],
  ["Sandslash", "Sablaireau"],
  ["Nidoran♀", "Nidoran♀"],
  ["Nidorina", "Nidorina"],
  ["Nidoqueen", "Nidoqueen"],
  ["Nidoran♂", "Nidoran♂"],
  ["Nidorino", "Nidorino"],
  ["Nidoking", "Nidoking"],
  ["Clefairy", "Méloféé"],
  ["Clefable", "Melodelfe"],
  ["Vulpix", "Goupix"],
  ["Ninetales", "Feunard"],
  ["Jigglypuff", "Rondoudou"],
  ["Wigglytuff", "Grodoudou"],
  ["Zubat", "Nosferapti"],
  ["Golbat", "Nosferalto"],
  ["Oddish", "Mystherbe"],
  ["Gloom", "Ortide"],
  ["Vileplume", "Rafflesia"],
  ["Paras", "Paras"],
  ["Parasect", "Parasect"],
  ["Venonat", "Mimitoss"],
  ["Venomoth", "Aéromite"],
  ["Diglett", "Taupiqueur"],
  ["Dugtrio", "Triopikeur"],
  ["Meowth", "Miaouss"],
  ["Persian", "Persian"],
  ["Psyduck", "Psykokwak"],
  ["Golduck", "Akwakwak"],
  ["Mankey", "Férosinge"],
  ["Primeape", "Colossinge"],
  ["Growlithe", "Caninos"],
  ["Arcanine", "Arcanin"],
  ["Poliwag", "Ptitard"],
  ["Poliwhirl", "Tetarte"],
  ["Poliwrath", "Tartard"],
  ["Abra", "Abra"],
  ["Kadabra", "Kadabra"],
  ["Alakazam", "Alakazam"],
  ["Machop", "Machoc"],
  ["Machoke", "Machopeur"],
  ["Machamp", "Mackogneur"],
  ["Bellsprout", "Chetiflor"],
  ["Weepinbell", "Boustiflor"],
  ["Victreebel", "Empiflor"],
  ["Tentacool", "Tentacool"],
  ["Tentacruel", "Tentacruel"],
  ["Geodude", "Racaillou"],
  ["Graveler", "Gravalanch"],
  ["Golem", "Grolem"],
  ["Ponyta", "Ponyta"],
  ["Rapidash", "Galopa"],
  ["Slowpoke", "Ramoloss"],
  ["Slowbro", "Flagadoss"],
  ["Magnemite", "Magneti"],
  ["Magneton", "Magneton"],
  ["Farfetch'd", "Canarticho"],
  ["Doduo", "Doduo"],
  ["Dodrio", "Dodrio"],
  ["Seel", "Otaria"],
  ["Dewgong", "Lamantine"],
  ["Grimer", "Tadmorv"],
  ["Muk", "Grotadmorv"],
  ["Shellder", "Kokiyas"],
  ["Cloyster", "Crustabri"],
  ["Gastly", "Fantominus"],
  ["Haunter", "Spectrum"],
  ["Gengar", "Ectoplasma"],
  ["Onix", "Onix"],
  ["Drowzee", "Soporifik"],
  ["Hypno", "Hypnomade"],
  ["Krabby", "Krabby"],
  ["Kingler", "Krabboss"],
  ["Voltorb", "Voltorbe"],
  ["Electrode", "Electrode"],
  ["Exeggcute", "Noeunoeuf"],
  ["Exeggutor", "Noadkoko"],
  ["Cubone", "Osselait"],
  ["Marowak", "Ossatueur"],
  ["Hitmonlee", "Kicklee"],
  ["Hitmonchan", "Tygnon"],
  ["Lickitung", "Excelangue"],
  ["Koffing", "Smogo"],
  ["Weezing", "Smogogo"],
  ["Rhyhorn", "Rhinocorne"],
  ["Rhydon", "Rhinoferos"],
  ["Chansey", "Leveinard"],
  ["Tangela", "Saquedeneu"],
  ["Kangaskhan", "Kangourex"],
  ["Horsea", "Hypotrempe"],
  ["Seadra", "Hypocéan"],
  ["Goldeen", "Poissirène"],
  ["Seaking", "Poissoroy"],
  ["Staryu", "Stari"],
  ["Starmie", "Staross"],
  ["Mr. Mime", "M. Mime"],
  ["Scyther", "Insécateur"],
  ["Jynx", "Lippoutou"],
  ["Electabuzz", "Elektek"],
  ["Magmar", "Magmar"],
  ["Pinsir", "Scarabrute"],
  ["Tauros", "Tauros"],
  ["Magikarp", "Magicarpe"],
  ["Gyarados", "Leviator"],
  ["Lapras", "Lokhlass"],
  ["Ditto", "Métamorph"],
  ["Eevee", "Évoli"],
  ["Vaporeon", "Aquali"],
  ["Jolteon", "Voltali"],
  ["Flareon", "Pyroli"],
  ["Porygon", "Porygon"],
  ["Omanyte", "Amonita"],
  ["Omastar", "Amonistar"],
  ["Kabuto", "Kabuto"],
  ["Kabutops", "Kabutops"],
  ["Aerodactyl", "Ptera"],
  ["Snorlax", "Ronflex"],
  ["Articuno", "Artikodin"],
  ["Zapdos", "Electhor"],
  ["Moltres", "Sulfura"],
  ["Dratini", "Minidraco"],
  ["Dragonair", "Draco"],
  ["Dragonite", "Dracolosse"],
  ["Mewtwo", "Mewtwo"],
  ["Mew", "Mew"],

  // ===== GENERATION 2 (Johto) =====
  ["Chikorita", "Germignon"],
  ["Bayleef", "Macronium"],
  ["Meganium", "Meganium"],
  ["Cyndaquil", "Héricendre"],
  ["Quilava", "Feurisson"],
  ["Typhlosion", "Typhlosion"],
  ["Totodile", "Kaiminus"],
  ["Croconaw", "Crocrodil"],
  ["Feraligatr", "Aligatueur"],
  ["Sentret", "Fouinette"],
  ["Furret", "Fouinar"],
  ["Hoothoot", "Hoothoot"],
  ["Noctowl", "Noarfang"],
  ["Ledyba", "Coxy"],
  ["Ledian", "Coxyclaque"],
  ["Spinarak", "Mimigal"],
  ["Ariados", "Migalos"],
  ["Crobat", "Nostenfer"],
  ["Chinchou", "Loupio"],
  ["Lanturn", "Lanturn"],
  ["Pichu", "Pichu"],
  ["Cleffa", "Mélo"],
  ["Igglybuff", "Toudoudou"],
  ["Togepi", "Togepi"],
  ["Togetic", "Togetic"],
  ["Natu", "Natu"],
  ["Xatu", "Xatu"],
  ["Mareep", "Wattouat"],
  ["Flaaffy", "Lainergie"],
  ["Ampharos", "Pharamp"],
  ["Bellossom", "Joliflor"],
  ["Marill", "Marill"],
  ["Azumarill", "Azumarill"],
  ["Sudowoodo", "Simularbre"],
  ["Politoed", "Tarpaud"],
  ["Hoppip", "Granivol"],
  ["Skiploom", "Floravol"],
  ["Jumpluff", "Cotovol"],
  ["Aipom", "Capumain"],
  ["Sunkern", "Tournegrin"],
  ["Sunflora", "Heliatronc"],
  ["Yanma", "Yanma"],
  ["Wooper", "Axoloto"],
  ["Quagsire", "Maraiste"],
  ["Espeon", "Mentali"],
  ["Umbreon", "Noctali"],
  ["Murkrow", "Cornobre"],
  ["Slowking", "Roigada"],
  ["Misdreavus", "Feuforeve"],
  ["Unown", "Zarbi"],
  ["Wobbuffet", "Qulbutoke"],
  ["Girafarig", "Girafarig"],
  ["Pineco", "Pomdepik"],
  ["Forretress", "Foretress"],
  ["Dunsparce", "Insolourdo"],
  ["Gligar", "Scorplane"],
  ["Steelix", "Steelix"],
  ["Snubbull", "Snubbull"],
  ["Granbull", "Granbull"],
  ["Qwilfish", "Qwilfish"],
  ["Scizor", "Cizayox"],
  ["Shuckle", "Caratroc"],
  ["Heracross", "Scarhino"],
  ["Sneasel", "Farfuret"],
  ["Teddiursa", "Teddiursa"],
  ["Ursaring", "Ursaring"],
  ["Slugma", "Limagma"],
  ["Magcargo", "Volcaropod"],
  ["Swinub", "Marcacrin"],
  ["Piloswine", "Cochignon"],
  ["Corsola", "Corayon"],
  ["Remoraid", "Remoraid"],
  ["Octillery", "Octillery"],
  ["Delibird", "Cadoizo"],
  ["Mantine", "Demanta"],
  ["Skarmory", "Airmure"],
  ["Houndour", "Malosse"],
  ["Houndoom", "Demolosse"],
  ["Kingdra", "Hyporoi"],
  ["Phanpy", "Phanpy"],
  ["Donphan", "Donphan"],
  ["Porygon2", "Porygon2"],
  ["Stantler", "Cerfrousse"],
  ["Smeargle", "Queulorior"],
  ["Tyrogue", "Debugant"],
  ["Hitmontop", "Kapoera"],
  ["Smoochum", "Lippouti"],
  ["Elekid", "Elekid"],
  ["Magby", "Magby"],
  ["Miltank", "Écremeuh"],
  ["Blissey", "Leuphorie"],
  ["Raikou", "Raikou"],
  ["Entei", "Entei"],
  ["Suicune", "Suicune"],
  ["Larvitar", "Embrylex"],
  ["Pupitar", "Ymphect"],
  ["Tyranitar", "Tyranocif"],
  ["Lugia", "Lugia"],
  ["Ho-Oh", "Ho-Oh"],
  ["Celebi", "Celebi"],

  // ===== GENERATION 3 (Hoenn) =====
  ["Treecko", "Arcko"],
  ["Grovyle", "Massko"],
  ["Sceptile", "Jungko"],
  ["Torchic", "Poussifeu"],
  ["Combusken", "Galifeu"],
  ["Blaziken", "Brasegali"],
  ["Mudkip", "Gobou"],
  ["Marshtomp", "Flobio"],
  ["Swampert", "Laggron"],
  ["Poochyena", "Medhyena"],
  ["Mightyena", "Grahyena"],
  ["Zigzagoon", "Zigzaton"],
  ["Linoone", "Lineon"],
  ["Wurmple", "Chenipotte"],
  ["Silcoon", "Armulys"],
  ["Beautifly", "Charmillon"],
  ["Cascoon", "Blindalys"],
  ["Dustox", "Papinox"],
  ["Lotad", "Nenupiot"],
  ["Lombre", "Lombre"],
  ["Ludicolo", "Ludicolo"],
  ["Seedot", "Grainipiot"],
  ["Nuzleaf", "Pifeuil"],
  ["Shiftry", "Tengalice"],
  ["Taillow", "Nirondelle"],
  ["Swellow", "Heledelle"],
  ["Wingull", "Goelise"],
  ["Pelipper", "Bekipan"],
  ["Ralts", "Tarsal"],
  ["Kirlia", "Kirlia"],
  ["Gardevoir", "Gardevoir"],
  ["Surskit", "Arakdo"],
  ["Masquerain", "Maskadra"],
  ["Shroomish", "Balignon"],
  ["Breloom", "Chapignon"],
  ["Slakoth", "Parecool"],
  ["Vigoroth", "Vigoroth"],
  ["Slaking", "Monaflemit"],
  ["Nincada", "Ningale"],
  ["Ninjask", "Ninjask"],
  ["Shedinja", "Munja"],
  ["Whismur", "Chuchmur"],
  ["Loudred", "Ramboum"],
  ["Exploud", "Brouhabam"],
  ["Makuhita", "Makuhita"],
  ["Hariyama", "Hariyama"],
  ["Azurill", "Azurill"],
  ["Nosepass", "Tarinor"],
  ["Skitty", "Skitty"],
  ["Delcatty", "Delcatty"],
  ["Sableye", "Tenefix"],
  ["Mawile", "Mysdibule"],
  ["Aron", "Galekid"],
  ["Lairon", "Galegon"],
  ["Aggron", "Galeking"],
  ["Meditite", "Meditikka"],
  ["Medicham", "Charmina"],
  ["Electrike", "Dynavolt"],
  ["Manectric", "Elecsprint"],
  ["Plusle", "Posipi"],
  ["Minun", "Negapi"],
  ["Volbeat", "Muciole"],
  ["Illumise", "Lumivole"],
  ["Roselia", "Roselia"],
  ["Gulpin", "Gloupti"],
  ["Swalot", "Avaltout"],
  ["Carvanha", "Carvanha"],
  ["Sharpedo", "Sharpedo"],
  ["Wailmer", "Wailmer"],
  ["Wailord", "Wailord"],
  ["Numel", "Chamallot"],
  ["Camerupt", "Camerupt"],
  ["Torkoal", "Chartor"],
  ["Spoink", "Spoink"],
  ["Grumpig", "Groret"],
  ["Spinda", "Spinda"],
  ["Trapinch", "Kraknoix"],
  ["Vibrava", "Vibraninf"],
  ["Flygon", "Libegon"],
  ["Cacnea", "Cacnea"],
  ["Cacturne", "Cacturne"],
  ["Swablu", "Tylton"],
  ["Altaria", "Altaria"],
  ["Zangoose", "Mangriff"],
  ["Seviper", "Seviper"],
  ["Lunatone", "Seleroc"],
  ["Solrock", "Solaroc"],
  ["Barboach", "Barloche"],
  ["Whiscash", "Barbicha"],
  ["Corphish", "Ecrapince"],
  ["Crawdaunt", "Colhomard"],
  ["Baltoy", "Balbuto"],
  ["Claydol", "Kaorine"],
  ["Lileep", "Lilia"],
  ["Cradily", "Vacilys"],
  ["Anorith", "Anorith"],
  ["Armaldo", "Armaldo"],
  ["Feebas", "Barpau"],
  ["Milotic", "Milobellus"],
  ["Castform", "Morpheo"],
  ["Kecleon", "Kecleon"],
  ["Shuppet", "Polichombr"],
  ["Banette", "Branette"],
  ["Duskull", "Skelenox"],
  ["Dusclops", "Teraclope"],
  ["Tropius", "Tropius"],
  ["Chimecho", "Eoko"],
  ["Absol", "Absol"],
  ["Wynaut", "Okeoké"],
  ["Snorunt", "Stalgamin"],
  ["Glalie", "Oniglali"],
  ["Spheal", "Obalie"],
  ["Sealeo", "Phogleur"],
  ["Walrein", "Kaimorse"],
  ["Clamperl", "Coquiperl"],
  ["Huntail", "Serpang"],
  ["Gorebyss", "Rosabyss"],
  ["Relicanth", "Relicanth"],
  ["Luvdisc", "Lovdisc"],
  ["Bagon", "Draby"],
  ["Shelgon", "Drackhaus"],
  ["Salamence", "Drattak"],
  ["Beldum", "Terhal"],
  ["Metang", "Metang"],
  ["Metagross", "Metalosse"],
  ["Regirock", "Regirock"],
  ["Regice", "Regice"],
  ["Registeel", "Registeel"],
  ["Latias", "Latias"],
  ["Latios", "Latios"],
  ["Kyogre", "Kyogre"],
  ["Groudon", "Groudon"],
  ["Rayquaza", "Rayquaza"],
  ["Jirachi", "Jirachi"],
  ["Deoxys", "Deoxys"],

  // ===== GENERATION 4 (Sinnoh) =====
  ["Turtwig", "Tortipouss"],
  ["Grotle", "Boskara"],
  ["Torterra", "Torterra"],
  ["Chimchar", "Ouisticram"],
  ["Monferno", "Chimpenfeu"],
  ["Infernape", "Simiabraz"],
  ["Piplup", "Tiplouf"],
  ["Prinplup", "Prinplouf"],
  ["Empoleon", "Pingoleon"],
  ["Starly", "Etourmi"],
  ["Staravia", "Etourvol"],
  ["Staraptor", "Etouraptor"],
  ["Bidoof", "Keunotor"],
  ["Bibarel", "Castorno"],
  ["Kricketot", "Crikzik"],
  ["Kricketune", "Melokrik"],
  ["Shinx", "Lixy"],
  ["Luxio", "Luxio"],
  ["Luxray", "Luxray"],
  ["Budew", "Rozbouton"],
  ["Roserade", "Roserade"],
  ["Cranidos", "Kranidos"],
  ["Rampardos", "Charkos"],
  ["Shieldon", "Dinoclier"],
  ["Bastiodon", "Bastiodon"],
  ["Burmy", "Cheniti"],
  ["Wormadam", "Cheniselle"],
  ["Mothim", "Papilord"],
  ["Combee", "Apitrini"],
  ["Vespiquen", "Apireine"],
  ["Pachirisu", "Pachirisu"],
  ["Buizel", "Mustebouee"],
  ["Floatzel", "Musteflott"],
  ["Cherubi", "Ceribou"],
  ["Cherrim", "Ceriflor"],
  ["Shellos", "Sancoki"],
  ["Gastrodon", "Tritosor"],
  ["Ambipom", "Capidextre"],
  ["Drifloon", "Baudrive"],
  ["Drifblim", "Grodrive"],
  ["Buneary", "Laporeille"],
  ["Lopunny", "Lockpin"],
  ["Mismagius", "Magireve"],
  ["Honchkrow", "Corboss"],
  ["Glameow", "Chaglam"],
  ["Purugly", "Chaffreux"],
  ["Chingling", "Korillon"],
  ["Stunky", "Moufouette"],
  ["Skuntank", "Moufflair"],
  ["Bronzor", "Archeomire"],
  ["Bronzong", "Archeodong"],
  ["Bonsly", "Manzai"],
  ["Mime Jr.", "Mime Jr."],
  ["Happiny", "Ptiravi"],
  ["Chatot", "Pijako"],
  ["Spiritomb", "Spiritomb"],
  ["Gible", "Griknot"],
  ["Gabite", "Carmache"],
  ["Garchomp", "Carchacrok"],
  ["Munchlax", "Goinfrex"],
  ["Riolu", "Riolu"],
  ["Lucario", "Lucario"],
  ["Hippopotas", "Hippopotas"],
  ["Hippowdon", "Hippodocus"],
  ["Skorupi", "Rapion"],
  ["Drapion", "Drascore"],
  ["Croagunk", "Cradopaud"],
  ["Toxicroak", "Coatox"],
  ["Carnivine", "Vortente"],
  ["Finneon", "Ecayon"],
  ["Lumineon", "Lumineon"],
  ["Mantyke", "Babimanta"],
  ["Snover", "Blizzi"],
  ["Abomasnow", "Blizzaroi"],
  ["Weavile", "Dimoret"],
  ["Magnezone", "Magnezone"],
  ["Lickilicky", "Coudlangue"],
  ["Rhyperior", "Rhinastoc"],
  ["Tangrowth", "Bouldeneu"],
  ["Electivire", "Elekable"],
  ["Magmortar", "Maganon"],
  ["Togekiss", "Togekiss"],
  ["Yanmega", "Yanmega"],
  ["Leafeon", "Phyllali"],
  ["Glaceon", "Givrali"],
  ["Gliscor", "Scorvol"],
  ["Mamoswine", "Mammochon"],
  ["Porygon-Z", "Porygon-Z"],
  ["Gallade", "Gallame"],
  ["Probopass", "Tarinorme"],
  ["Dusknoir", "Noctunoir"],
  ["Froslass", "Momartik"],
  ["Rotom", "Motisma"],
  ["Uxie", "Créfollet"],
  ["Mesprit", "Créhelf"],
  ["Azelf", "Créfahdet"],
  ["Dialga", "Dialga"],
  ["Palkia", "Palkia"],
  ["Heatran", "Heatran"],
  ["Regigigas", "Regigigas"],
  ["Giratina", "Giratina"],
  ["Cresselia", "Cresselia"],
  ["Phione", "Phione"],
  ["Manaphy", "Manaphy"],
  ["Darkrai", "Darkrai"],
  ["Shaymin", "Shaymin"],
  ["Arceus", "Arceus"],

  // ===== GENERATION 5 (Unova) =====
  ["Victini", "Victini"],
  ["Snivy", "Vipélierre"],
  ["Servine", "Lianaja"],
  ["Serperior", "Majaspic"],
  ["Tepig", "Gruikui"],
  ["Pignite", "Grotichon"],
  ["Emboar", "Roitiflam"],
  ["Oshawott", "Moustillon"],
  ["Dewott", "Mateloutre"],
  ["Samurott", "Clamiral"],
  ["Patrat", "Ratentif"],
  ["Watchog", "Miradar"],
  ["Lillipup", "Ponchiot"],
  ["Herdier", "Ponchien"],
  ["Stoutland", "Mastouffe"],
  ["Purrloin", "Chacripan"],
  ["Liepard", "Leopardus"],
  ["Pansage", "Feuillajou"],
  ["Simisage", "Feuiloutan"],
  ["Pansear", "Flamajou"],
  ["Simisear", "Flamoutan"],
  ["Panpour", "Flotajou"],
  ["Simipour", "Flotoutan"],
  ["Munna", "Munna"],
  ["Musharna", "Musharna"],
  ["Pidove", "Poichigeon"],
  ["Tranquill", "Colombeau"],
  ["Unfezant", "Deflaisan"],
  ["Blitzle", "Zebibron"],
  ["Zebstrika", "Zeblitz"],
  ["Roggenrola", "Nodulithe"],
  ["Boldore", "Geolithe"],
  ["Gigalith", "Gigalithe"],
  ["Woobat", "Chovsourir"],
  ["Swoobat", "Rhinolove"],
  ["Drilbur", "Rototaupe"],
  ["Excadrill", "Minotaupe"],
  ["Audino", "Nanmeouie"],
  ["Timburr", "Charpenti"],
  ["Gurdurr", "Ouvrifier"],
  ["Conkeldurr", "Betochef"],
  ["Tympole", "Tritonde"],
  ["Palpitoad", "Batracne"],
  ["Seismitoad", "Crapustule"],
  ["Throh", "Judokrak"],
  ["Sawk", "Karaclee"],
  ["Sewaddle", "Larveyette"],
  ["Swadloon", "Couverdure"],
  ["Leavanny", "Manternel"],
  ["Venipede", "Venipatte"],
  ["Whirlipede", "Scobolide"],
  ["Scolipede", "Brutapode"],
  ["Cottonee", "Doudouvet"],
  ["Whimsicott", "Farfaduvet"],
  ["Petilil", "Chlorobule"],
  ["Lilligant", "Fragilady"],
  ["Basculin", "Bargantua"],
  ["Sandile", "Mascaiman"],
  ["Krokorok", "Escroco"],
  ["Krookodile", "Crocorible"],
  ["Darumaka", "Darumarond"],
  ["Darmanitan", "Darumacho"],
  ["Maractus", "Maracachi"],
  ["Dwebble", "Crabicoque"],
  ["Crustle", "Crabaraque"],
  ["Scraggy", "Baggiguane"],
  ["Scrafty", "Baggaid"],
  ["Sigilyph", "Cryptero"],
  ["Yamask", "Tutafeh"],
  ["Cofagrigus", "Tutankafer"],
  ["Tirtouga", "Carapagos"],
  ["Carracosta", "Megapagos"],
  ["Archen", "Arkeoaptyl"],
  ["Archeops", "Aeropteryx"],
  ["Trubbish", "Miamiasme"],
  ["Garbodor", "Miasmax"],
  ["Zorua", "Zorua"],
  ["Zoroark", "Zoroark"],
  ["Minccino", "Chinchidou"],
  ["Cinccino", "Pashmilla"],
  ["Gothita", "Scrutella"],
  ["Gothorita", "Mesmerella"],
  ["Gothitelle", "Sidérella"],
  ["Solosis", "Nucléos"],
  ["Duosion", "Méios"],
  ["Reuniclus", "Symbios"],
  ["Ducklett", "Couaneton"],
  ["Swanna", "Lakmecygne"],
  ["Vanillite", "Sorbébé"],
  ["Vanillish", "Sorboul"],
  ["Vanilluxe", "Sorbouboul"],
  ["Deerling", "Vivaldaim"],
  ["Sawsbuck", "Haydaim"],
  ["Emolga", "Emolga"],
  ["Karrablast", "Carabing"],
  ["Escavalier", "Lançargot"],
  ["Foongus", "Trompignon"],
  ["Amoonguss", "Gaulet"],
  ["Frillish", "Viskuse"],
  ["Jellicent", "Moyade"],
  ["Alomomola", "Mamanbo"],
  ["Joltik", "Statitik"],
  ["Galvantula", "Mygavolt"],
  ["Ferroseed", "Grindur"],
  ["Ferrothorn", "Noacier"],
  ["Klink", "Tic"],
  ["Klang", "Clic"],
  ["Klinklang", "Cliticlic"],
  ["Tynamo", "Anchwatt"],
  ["Eelektrik", "Lampéroie"],
  ["Eelektross", "Ohmassacre"],
  ["Elgyem", "Lewsor"],
  ["Beheeyem", "Neitram"],
  ["Litwick", "Funécire"],
  ["Lampent", "Mélancolux"],
  ["Chandelure", "Lugulabre"],
  ["Axew", "Coupenotte"],
  ["Fraxure", "Incisache"],
  ["Haxorus", "Tranchodon"],
  ["Cubchoo", "Polarhume"],
  ["Beartic", "Polagriffe"],
  ["Cryogonal", "Hexagel"],
  ["Shelmet", "Escargaume"],
  ["Accelgor", "Limaspeed"],
  ["Stunfisk", "Limonde"],
  ["Mienfoo", "Kungfouine"],
  ["Mienshao", "Shaofouine"],
  ["Druddigon", "Drakkarmin"],
  ["Golett", "Gringolem"],
  ["Golurk", "Golemastoc"],
  ["Pawniard", "Scalpion"],
  ["Bisharp", "Scalproie"],
  ["Bouffalant", "Frison"],
  ["Rufflet", "Furaiglon"],
  ["Braviary", "Gueriaigle"],
  ["Vullaby", "Vostourno"],
  ["Mandibuzz", "Vaututrice"],
  ["Heatmor", "Aflamanoir"],
  ["Durant", "Fermite"],
  ["Deino", "Solochi"],
  ["Zweilous", "Diamat"],
  ["Hydreigon", "Trioxhydre"],
  ["Larvesta", "Pyronille"],
  ["Volcarona", "Pyrax"],
  ["Cobalion", "Cobaltium"],
  ["Terrakion", "Terrakium"],
  ["Virizion", "Viridium"],
  ["Tornadus", "Boreas"],
  ["Thundurus", "Fulguris"],
  ["Reshiram", "Reshiram"],
  ["Zekrom", "Zekrom"],
  ["Landorus", "Demeteros"],
  ["Kyurem", "Kyurem"],
  ["Keldeo", "Keldeo"],
  ["Meloetta", "Meloetta"],
  ["Genesect", "Genesect"],

  // ===== GENERATION 6 (Kalos) =====
  ["Chespin", "Marisson"],
  ["Quilladin", "Boguerisse"],
  ["Chesnaught", "Blindepique"],
  ["Fennekin", "Feunnec"],
  ["Braixen", "Roussil"],
  ["Delphox", "Goupelin"],
  ["Froakie", "Grenousse"],
  ["Frogadier", "Croâporal"],
  ["Greninja", "Amphinobi"],
  ["Bunnelby", "Sapereau"],
  ["Diggersby", "Excavarenne"],
  ["Fletchling", "Passerouge"],
  ["Fletchinder", "Braisillon"],
  ["Talonflame", "Flambusard"],
  ["Scatterbug", "Lepidonille"],
  ["Spewpa", "Pérégrain"],
  ["Vivillon", "Prismillon"],
  ["Litleo", "Hélionceau"],
  ["Pyroar", "Némélios"],
  ["Flabébé", "Flabébé"],
  ["Floette", "Floette"],
  ["Florges", "Florges"],
  ["Skiddo", "Cabriolaine"],
  ["Gogoat", "Chevroum"],
  ["Pancham", "Pandespiègle"],
  ["Pangoro", "Pandarbare"],
  ["Furfrou", "Couafarel"],
  ["Espurr", "Psystigri"],
  ["Meowstic", "Mistigrix"],
  ["Honedge", "Monorpale"],
  ["Doublade", "Dimoclès"],
  ["Aegislash", "Exagide"],
  ["Spritzee", "Fluvetin"],
  ["Aromatisse", "Cocotine"],
  ["Swirlix", "Sucroquin"],
  ["Slurpuff", "Cupcanaille"],
  ["Inkay", "Sepiatop"],
  ["Malamar", "Sepiatroce"],
  ["Binacle", "Opermine"],
  ["Barbaracle", "Golgopathe"],
  ["Skrelp", "Venalgue"],
  ["Dragalge", "Kravarech"],
  ["Clauncher", "Flingouste"],
  ["Clawitzer", "Gamblast"],
  ["Helioptile", "Galvaran"],
  ["Heliolisk", "Iguolta"],
  ["Tyrunt", "Ptyranidur"],
  ["Tyrantrum", "Rexillius"],
  ["Amaura", "Amagara"],
  ["Aurorus", "Dragmara"],
  ["Sylveon", "Nymphali"],
  ["Hawlucha", "Brutalibré"],
  ["Dedenne", "Dedenne"],
  ["Carbink", "Strassie"],
  ["Goomy", "Mucuscule"],
  ["Sliggoo", "Colimucus"],
  ["Goodra", "Muplodocus"],
  ["Klefki", "Trousselin"],
  ["Phantump", "Brocélôme"],
  ["Trevenant", "Desséliande"],
  ["Pumpkaboo", "Pitrouille"],
  ["Gourgeist", "Banshitrouye"],
  ["Bergmite", "Grelaçon"],
  ["Avalugg", "Séracrawl"],
  ["Noibat", "Sonistrelle"],
  ["Noivern", "Bruyverne"],
  ["Xerneas", "Xerneas"],
  ["Yveltal", "Yveltal"],
  ["Zygarde", "Zygarde"],
  ["Diancie", "Diancie"],
  ["Hoopa", "Hoopa"],
  ["Volcanion", "Volcanion"],

  // ===== GENERATION 7 (Alola) =====
  ["Rowlet", "Brindibou"],
  ["Dartrix", "Efflèche"],
  ["Decidueye", "Archéduc"],
  ["Litten", "Flamiaou"],
  ["Torracat", "Matoufeu"],
  ["Incineroar", "Félinferno"],
  ["Popplio", "Otaquin"],
  ["Brionne", "Otarlette"],
  ["Primarina", "Oratoria"],
  ["Pikipek", "Picassaut"],
  ["Trumbeak", "Piclairon"],
  ["Toucannon", "Bazoucan"],
  ["Yungoos", "Manglouton"],
  ["Gumshoos", "Argouste"],
  ["Grubbin", "Larvibule"],
  ["Charjabug", "Chrysapile"],
  ["Vikavolt", "Lucanon"],
  ["Crabrawler", "Crabagarre"],
  ["Crabominable", "Crabominable"],
  ["Oricorio", "Plumeline"],
  ["Cutiefly", "Bombydou"],
  ["Ribombee", "Rubombelle"],
  ["Rockruff", "Rocabot"],
  ["Lycanroc", "Lougaroc"],
  ["Wishiwashi", "Froussardine"],
  ["Mareanie", "Vorastérie"],
  ["Toxapex", "Prédastérie"],
  ["Mudbray", "Tiboudet"],
  ["Mudsdale", "Bourrinos"],
  ["Dewpider", "Araqua"],
  ["Araquanid", "Tarenbulle"],
  ["Fomantis", "Mimantis"],
  ["Lurantis", "Floramantis"],
  ["Morelull", "Spododo"],
  ["Shiinotic", "Lampignon"],
  ["Salandit", "Tritox"],
  ["Salazzle", "Malamandre"],
  ["Stufful", "Nounourson"],
  ["Bewear", "Chelours"],
  ["Bounsweet", "Croquine"],
  ["Steenee", "Candine"],
  ["Tsareena", "Sucreine"],
  ["Comfey", "Guérilande"],
  ["Oranguru", "Gouroutan"],
  ["Passimian", "Quartermac"],
  ["Wimpod", "Sovkipou"],
  ["Golisopod", "Sarmuraï"],
  ["Sandygast", "Bacabouh"],
  ["Palossand", "Trépassable"],
  ["Pyukumuku", "Concombaffe"],
  ["Type: Null", "Type:0"],
  ["Silvally", "Silvallié"],
  ["Minior", "Météno"],
  ["Komala", "Dodoala"],
  ["Turtonator", "Boumata"],
  ["Togedemaru", "Togedemaru"],
  ["Mimikyu", "Mimiqui"],
  ["Bruxish", "Denticrisse"],
  ["Drampa", "Draïeul"],
  ["Dhelmise", "Sinistrail"],
  ["Jangmo-o", "Bébécaille"],
  ["Hakamo-o", "Écaïd"],
  ["Kommo-o", "Ékaïser"],
  ["Tapu Koko", "Tokorico"],
  ["Tapu Lele", "Tokopiyon"],
  ["Tapu Bulu", "Tokotoro"],
  ["Tapu Fini", "Tokopisco"],
  ["Cosmog", "Cosmog"],
  ["Cosmoem", "Cosmovum"],
  ["Solgaleo", "Solgaleo"],
  ["Lunala", "Lunala"],
  ["Nihilego", "Zéroïd"],
  ["Buzzwole", "Mouscoto"],
  ["Pheromosa", "Cancrelove"],
  ["Xurkitree", "Câblifère"],
  ["Celesteela", "Bamboiselle"],
  ["Kartana", "Katagami"],
  ["Guzzlord", "Engloutyran"],
  ["Necrozma", "Necrozma"],
  ["Magearna", "Magearna"],
  ["Marshadow", "Marshadow"],
  ["Poipole", "Vemini"],
  ["Naganadel", "Mandrillon"],
  ["Stakataka", "Ama-Ama"],
  ["Blacephalon", "Pierroteknik"],
  ["Zeraora", "Zeraora"],
  ["Meltan", "Meltan"],
  ["Melmetal", "Melmetal"],

  // ===== GENERATION 8 (Galar) =====
  ["Grookey", "Ouistempo"],
  ["Thwackey", "Badabouin"],
  ["Rillaboom", "Gorythmic"],
  ["Scorbunny", "Flambino"],
  ["Raboot", "Lapyro"],
  ["Cinderace", "Pyrobut"],
  ["Sobble", "Larméléon"],
  ["Drizzile", "Arrozard"],
  ["Inteleon", "Lézargus"],
  ["Skwovet", "Rongourmand"],
  ["Greedent", "Rongrigou"],
  ["Rookidee", "Minisange"],
  ["Corvisquire", "Bleuseille"],
  ["Corviknight", "Corvaillus"],
  ["Blipbug", "Larvadar"],
  ["Dottler", "Coléodôme"],
  ["Orbeetle", "Astronelle"],
  ["Nickit", "Goupilou"],
  ["Thievul", "Roublenard"],
  ["Gossifleur", "Tournicoton"],
  ["Eldegoss", "Blancoton"],
  ["Wooloo", "Moumouton"],
  ["Dubwool", "Moumouflon"],
  ["Chewtle", "Khélocrok"],
  ["Drednaw", "Torgamord"],
  ["Yamper", "Voltoutou"],
  ["Boltund", "Fulgudog"],
  ["Rolycoly", "Charbi"],
  ["Carkol", "Wagomine"],
  ["Coalossal", "Monthracite"],
  ["Applin", "Verpom"],
  ["Flapple", "Pomdrapi"],
  ["Appletun", "Dratatin"],
  ["Silicobra", "Dunaja"],
  ["Sandaconda", "Dunaconda"],
  ["Cramorant", "Nigosier"],
  ["Arrokuda", "Embrochet"],
  ["Barraskewda", "Hastacuda"],
  ["Toxel", "Toxizap"],
  ["Toxtricity", "Salarsen"],
  ["Sizzlipede", "Grillepattes"],
  ["Centiskorch", "Scolocendre"],
  ["Clobbopus", "Poulpaf"],
  ["Grapploct", "Krakos"],
  ["Sinistea", "Théffroi"],
  ["Polteageist", "Polthégeist"],
  ["Hatenna", "Bibichut"],
  ["Hattrem", "Chapotus"],
  ["Hatterene", "Sorcilence"],
  ["Impidimp", "Grimalin"],
  ["Morgrem", "Fourbelin"],
  ["Grimmsnarl", "Angoliath"],
  ["Obstagoon", "Ixon"],
  ["Perrserker", "Berserkatt"],
  ["Cursola", "Corayôme"],
  ["Sirfetch'd", "Palarticho"],
  ["Mr. Rime", "M. Glaquette"],
  ["Runerigus", "Tutétékri"],
  ["Milcery", "Crèmy"],
  ["Alcremie", "Charmilly"],
  ["Falinks", "Hexadron"],
  ["Pincurchin", "Wattapik"],
  ["Snom", "Frissonille"],
  ["Frosmoth", "Beldeneige"],
  ["Stonjourner", "Dolman"],
  ["Eiscue", "Bekaglaçon"],
  ["Indeedee", "Wimessir"],
  ["Morpeko", "Morpeko"],
  ["Cufant", "Charibari"],
  ["Copperajah", "Pachyradjah"],
  ["Dracozolt", "Galvagon"],
  ["Arctozolt", "Galvagla"],
  ["Dracovish", "Hydragon"],
  ["Arctovish", "Hydragla"],
  ["Duraludon", "Duralugon"],
  ["Dreepy", "Fantyrm"],
  ["Drakloak", "Dispareptil"],
  ["Dragapult", "Lanssorien"],
  ["Zacian", "Zacian"],
  ["Zamazenta", "Zamazenta"],
  ["Eternatus", "Eternatus"],
  ["Kubfu", "Wushours"],
  ["Urshifu", "Shifours"],
  ["Zarude", "Zarude"],
  ["Regieleki", "Regieleki"],
  ["Regidrago", "Regidrago"],
  ["Glastrier", "Blizzeval"],
  ["Spectrier", "Spectreval"],
  ["Calyrex", "Sylveroy"],

  // ===== GENERATION 9 (Paldea) =====
  ["Sprigatito", "Poussacha"],
  ["Floragato", "Matourgeon"],
  ["Meowscarada", "Miascarade"],
  ["Fuecoco", "Chochodile"],
  ["Crocalor", "Crocembre"],
  ["Skeledirge", "Flâmigator"],
  ["Quaxly", "Coiffeton"],
  ["Quaxwell", "Canarbello"],
  ["Quaquaval", "Palmaval"],
  ["Lechonk", "Gourmelet"],
  ["Oinkologne", "Fragroin"],
  ["Tarountula", "Tissenboule"],
  ["Spidops", "Filentrappe"],
  ["Nymble", "Lilliterelle"],
  ["Lokix", "Gambex"],
  ["Pawmi", "Pohm"],
  ["Pawmo", "Pohmotte"],
  ["Pawmot", "Pohmarmotte"],
  ["Tandemaus", "Compagnol"],
  ["Maushold", "Famignol"],
  ["Fidough", "Pâtachiot"],
  ["Dachsbun", "Briochien"],
  ["Smoliv", "Olivini"],
  ["Dolliv", "Olivado"],
  ["Arboliva", "Arboliva"],
  ["Squawkabilly", "Tapatoès"],
  ["Nacli", "Selutin"],
  ["Naclstack", "Alusel"],
  ["Garganacl", "Gigansel"],
  ["Charcadet", "Charbambin"],
  ["Armarouge", "Carmadura"],
  ["Ceruledge", "Malvalame"],
  ["Tadbulb", "Têtampoule"],
  ["Bellibolt", "Ampibidou"],
  ["Wattrel", "Zapétrel"],
  ["Kilowattrel", "Fulgulairo"],
  ["Maschiff", "Grondogue"],
  ["Mabosstiff", "Dogrino"],
  ["Shroodle", "Gribouraigne"],
  ["Grafaiai", "Tag-Tag"],
  ["Bramblin", "Virovent"],
  ["Brambleghast", "Virevorreur"],
  ["Toedscool", "Terracool"],
  ["Toedscruel", "Terracruel"],
  ["Klawf", "Craparoi"],
  ["Capsakid", "Pimito"],
  ["Scovillain", "Scovilain"],
  ["Rellor", "Léboulérou"],
  ["Rabsca", "Scarabrillant"],
  ["Flittle", "Flotillon"],
  ["Espathra", "Cléopsytra"],
  ["Tinkatink", "Forgerette"],
  ["Tinkatuff", "Forgella"],
  ["Tinkaton", "Forgelina"],
  ["Wiglett", "Taupikeau"],
  ["Wugtrio", "Triopikeau"],
  ["Bombirdier", "Lestombaile"],
  ["Finizen", "Dofin"],
  ["Palafin", "Superdofin"],
  ["Varoom", "Vrombi"],
  ["Revavroom", "Vrombotor"],
  ["Cyclizar", "Motorizard"],
  ["Orthworm", "Vermidrill"],
  ["Glimmet", "Germéclat"],
  ["Glimmora", "Floréclat"],
  ["Greavard", "Toutombe"],
  ["Houndstone", "Tomberro"],
  ["Flamigo", "Flamigo"],
  ["Cetoddle", "Piétacé"],
  ["Cetitan", "Balbalèze"],
  ["Veluza", "Délestin"],
  ["Dondozo", "Dorlondozo"],
  ["Tatsugiri", "Nigirigon"],
  ["Annihilape", "Courrousinge"],
  ["Clodsire", "Terraiste"],
  ["Farigiraf", "Farigiraf"],
  ["Dudunsparce", "Deusolourdo"],
  ["Kingambit", "Scalpereur"],
  ["Great Tusk", "Fort-Ivoire"],
  ["Scream Tail", "Hurle-Queue"],
  ["Brute Bonnet", "Fongus-Furie"],
  ["Flutter Mane", "Flotte-Mane"],
  ["Slither Wing", "Rampe-Ailes"],
  ["Sandy Shocks", "Pelage-Sablé"],
  ["Iron Treads", "Roue-de-Fer"],
  ["Iron Bundle", "Hotte-de-Fer"],
  ["Iron Hands", "Paume-de-Fer"],
  ["Iron Jugulis", "Tête-de-Fer"],
  ["Iron Moth", "Mite-de-Fer"],
  ["Iron Thorns", "Épine-de-Fer"],
  ["Frigibax", "Frigodo"],
  ["Arctibax", "Cryodo"],
  ["Baxcalibur", "Glaivodo"],
  ["Gimmighoul", "Mordudor"],
  ["Gholdengo", "Dorédar"],
  ["Wo-Chien", "Chongjian"],
  ["Chien-Pao", "Baojian"],
  ["Ting-Lu", "Dinglu"],
  ["Chi-Yu", "Yuyu"],
  ["Roaring Moon", "Rugit-Lune"],
  ["Iron Valiant", "Garde-de-Fer"],
  ["Koraidon", "Koraidon"],
  ["Miraidon", "Miraidon"],
  ["Walking Wake", "Bouillond'eau"],
  ["Iron Leaves", "Feuille-de-Fer"],
  ["Dipplin", "Pomdorma"],
  ["Poltchageist", "Poltchageist"],
  ["Sinistcha", "Sinistcha"],
  ["Okidogi", "Félicanis"],
  ["Munkidori", "Fortusimia"],
  ["Fezandipiti", "Favianos"],
  ["Ogerpon", "Ogerpon"],
  ["Archaludon", "Pondralugon"],
  ["Hydrapple", "Pomdramour"],
  ["Gouging Fire", "Feu-Perçant"],
  ["Raging Bolt", "Éclair-Furieux"],
  ["Iron Boulder", "Roc-de-Fer"],
  ["Iron Crown", "Couronne-de-Fer"],
  ["Terapagos", "Terapagos"],
  ["Pecharunt", "Pêchaminus"],
];

/**
 * Normalise une chaine : minuscules + suppression des accents
 * Permet de matcher "Salamèche" == "Salameche", "Évoli" == "Evoli", etc.
 */
function normalize(str: string): string {
  return str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, ""); // supprime les diacritiques
}

// Build lookup maps (clés normalisées sans accents)
const frToEn = new Map<string, string>();
const enToFr = new Map<string, string>();

for (const [en, fr] of NAME_PAIRS) {
  const enNorm = normalize(en);
  const frNorm = normalize(fr);
  // Seulement si les noms sont différents
  if (enNorm !== frNorm) {
    frToEn.set(frNorm, en);   // clé FR normalisée → nom EN officiel
    enToFr.set(enNorm, fr);   // clé EN normalisée → nom FR officiel
  }
}

/**
 * Traduit un nom Pokemon du francais vers l'anglais (insensible aux accents)
 */
export function frenchToEnglish(name: string): string | null {
  return frToEn.get(normalize(name)) || null;
}

/**
 * Traduit un nom Pokemon de l'anglais vers le francais (insensible aux accents)
 */
export function englishToFrench(name: string): string | null {
  return enToFr.get(normalize(name)) || null;
}

/**
 * Retourne toutes les variantes de nom pour une recherche
 * Inclut le nom original + traduction(s) si disponible(s)
 * Insensible aux accents et à la casse
 */
export function getSearchNames(query: string): string[] {
  const names = [query];

  // Nom français → récupère l'anglais
  const enName = frenchToEnglish(query);
  if (enName && normalize(enName) !== normalize(query)) {
    names.push(enName);
  }

  // Nom anglais → récupère le français
  const frName = englishToFrench(query);
  if (frName && normalize(frName) !== normalize(query)) {
    names.push(frName);
  }

  return names;
}

/**
 * Retourne le nom francais d'un Pokemon (ou le nom original si pas de traduction)
 */
export function getFrenchName(englishName: string): string {
  return englishToFrench(englishName) || englishName;
}
